apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: customer
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: customer
    spec:
      containers:
        - name: customer
          image: ccteam4acr.azurecr.io/customer
          ports:
            - containerPort: 8083